#!/bin/bash


info=$(upower -i $(upower -e | grep 'BAT0'))
pwr=$(echo -n "$info" | grep 'percentage' | cut -d : -f 2 | sed -e 's/^[[:space:]]*//' -e 's/%$//')
state=$(echo -n "$info" | grep 'state' | cut -d : -f 2 | sed -e 's/^[[:space:]]*//')
sounds=/usr/share/sounds/freedesktop/stereo

if [ $2 -le $1 ]; then
    echo "Error: '$2' <= '$1'" 1>&2
    exit 1
fi

if [ $pwr -le $1 -a $state == discharging ]; then
    paplay $sounds/service-login.oga
elif [ $pwr -ge $2 -a $state == charging ]; then
    paplay $sounds/service-logout.oga
fi

exit 0
