#!/bin/bash


scriptname=`basename $0`

# check number of args
if [ $# -le 1 ]; then
    echo Usage: $scriptname NUM1 NUM2...
    exit 0
fi

isnum()
{
    re='^(-|\+)?([1-9][0-9]*|0)$'
    if [[ $1 =~ $re ]]; then
	echo -n 1
    else
	echo -n 0
    fi
}

findmax()
{
    max=$1
    for num in $*; do
	if [ `isnum $num` -eq 0 ]; then
	    echo $scriptname: $num: Not a valid number
	    exit 1
	fi

	if [ $num -gt $max ]; then
	    max=$num
	fi
    done

    echo -n $max
}

max=`findmax $*`
while read line; do
    max=`findmax $line $max`
done < /dev/stdin

echo $max
exit 0
